"""empty message

Revision ID: 0b7696772c68
Revises: ea995dd7a974
Create Date: 2023-09-25 14:28:25.370984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b7696772c68'
down_revision = 'ea995dd7a974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('product_transactions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['customer_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_transactions_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
