"""Add Transaction Code

Revision ID: 17671723be77
Revises: 39f2958e9b7c
Create Date: 2023-09-17 15:48:48.765332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17671723be77'
down_revision = '39f2958e9b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laundry_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_code', sa.String(length=25), nullable=True))

    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_code', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.drop_column('transaction_code')

    with op.batch_alter_table('laundry_transactions', schema=None) as batch_op:
        batch_op.drop_column('transaction_code')

    # ### end Alembic commands ###
