"""empty message

Revision ID: 268923863c77
Revises: 534160ad61d6
Create Date: 2023-09-01 23:23:00.708740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268923863c77'
down_revision = '534160ad61d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('total_sold')

    # ### end Alembic commands ###
