"""minor

Revision ID: 2e2f96f0d1da
Revises: 7f687409269c
Create Date: 2023-08-25 23:37:44.490339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e2f96f0d1da'
down_revision = '7f687409269c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profil_picture', sa.String(length=50), nullable=True))
        batch_op.drop_column('profil_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profil_pic', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('profil_picture')

    # ### end Alembic commands ###
