"""minor update

Revision ID: 35a3d332a646
Revises: 2e2f96f0d1da
Create Date: 2023-08-25 23:38:46.113873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35a3d332a646'
down_revision = '2e2f96f0d1da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=50), nullable=True))
        batch_op.drop_column('profil_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profil_picture', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
