"""Add Cashier Id TO Laundry fix typo

Revision ID: 39f2958e9b7c
Revises: 80c823d71774
Create Date: 2023-09-11 20:04:54.564502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39f2958e9b7c'
down_revision = '80c823d71774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laundry_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashier_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('laundry_transactions_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['cashier_id'], ['id'])
        batch_op.drop_column('cashiser_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laundry_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashiser_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('laundry_transactions_ibfk_3', 'users', ['cashiser_id'], ['id'])
        batch_op.drop_column('cashier_id')

    # ### end Alembic commands ###
