"""Minor Adjustment

Revision ID: 4a3cdaaf8324
Revises: 268923863c77
Create Date: 2023-09-01 23:26:13.210459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a3cdaaf8324'
down_revision = '268923863c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=True))
        batch_op.drop_column('product_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_code', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
