"""empty message

Revision ID: 534160ad61d6
Revises: 4b959a8c2d5d
Create Date: 2023-09-01 23:21:50.835241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '534160ad61d6'
down_revision = '4b959a8c2d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_types', ['product_type'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('date_modified')
        batch_op.drop_column('product_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_modified', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_ibfk_1', 'product_types', ['product_type_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('last_modified')
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
