"""al

Revision ID: 64c31a379589
Revises: e6cb435050dd
Create Date: 2023-08-22 14:02:35.426176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64c31a379589'
down_revision = 'e6cb435050dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('room', sa.String(length=10), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('submit_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submit_data', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    with op.batch_alter_table('registration_profiles', schema=None) as batch_op:
        batch_op.drop_column('room')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
