"""empty message

Revision ID: 7d51d3cf4859
Revises: ccb3ca5d5184
Create Date: 2023-08-25 15:05:50.885796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d51d3cf4859'
down_revision = 'ccb3ca5d5184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transaction_details', schema=None) as batch_op:
        batch_op.drop_constraint('product_transaction_details_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_transactions', ['transaction_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transaction_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_transaction_details_ibfk_1', 'product_transactions', ['transaction_id'], ['id'])

    # ### end Alembic commands ###
