"""Minor Adjustment

Revision ID: 9a70c8810b1c
Revises: 4a3cdaaf8324
Create Date: 2023-09-01 23:27:45.557501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a70c8810b1c'
down_revision = '4a3cdaaf8324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.Integer(), nullable=True))
        batch_op.drop_column('total_sold')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sold', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('sold')

    # ### end Alembic commands ###
