"""empty message

Revision ID: bc014e26d1d4
Revises: 0ddb1f9cffea
Create Date: 2023-08-22 13:13:59.538432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc014e26d1d4'
down_revision = '0ddb1f9cffea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_profiles', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('user_class')
        batch_op.drop_column('room')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('user_class', mysql.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
