"""Update 3

Revision ID: c359b4d38cb3
Revises: bc014e26d1d4
Create Date: 2023-08-22 13:25:45.266302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c359b4d38cb3'
down_revision = 'bc014e26d1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submit_data', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('submit_data')

    # ### end Alembic commands ###
