"""empty message

Revision ID: ca735e5cee61
Revises: 7d51d3cf4859
Create Date: 2023-08-25 15:09:16.316659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca735e5cee61'
down_revision = '7d51d3cf4859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transaction_attributes', schema=None) as batch_op:
        batch_op.drop_constraint('product_transaction_attributes_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('product_transaction_attributes_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['payment_approve_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['deliver_by'], ['id'])

    with op.batch_alter_table('product_transaction_details', schema=None) as batch_op:
        batch_op.drop_constraint('product_transaction_details_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product_transactions', ['transaction_id'], ['id'])

    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('product_transactions_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('product_transactions_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['cashier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_transactions_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('product_transactions_ibfk_2', 'users', ['cashier_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('product_transaction_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_transaction_details_ibfk_3', 'product_transactions', ['transaction_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('product_transaction_attributes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_transaction_attributes_ibfk_2', 'users', ['payment_approve_by'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('product_transaction_attributes_ibfk_3', 'users', ['deliver_by'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
