"""Update

Revision ID: e6cb435050dd
Revises: c359b4d38cb3
Create Date: 2023-08-22 13:28:11.399177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cb435050dd'
down_revision = 'c359b4d38cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_class', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_profiles', schema=None) as batch_op:
        batch_op.drop_column('user_class')

    # ### end Alembic commands ###
