"""empty message

Revision ID: ea995dd7a974
Revises: 17671723be77
Create Date: 2023-09-25 10:59:36.735746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea995dd7a974'
down_revision = '17671723be77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_transactions', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
